In [3]:
l=range(1000000)

In [4]:
%time for i in l:    i*7

Wall time: 303 ms


In [5]:
import numpy as np

In [6]:
l=np.arange(1000000)

In [7]:
%time l*7

Wall time: 6.98 ms


array([      0,       7,      14, ..., 6999979, 6999986, 6999993])

In [8]:
l1=range(1000000)
l2=range(1000000)

In [17]:
%time for i in range(1000000): l1[i]+l2[i]

Wall time: 818 ms


In [10]:
a1=np.arange(1000000)
a2=np.arange(1000000)

In [11]:
%time a1+a2

Wall time: 6.98 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [13]:
l1=[1,4,5,7,9]
l2=[11,14,15,17,19]

In [16]:
for i in range(5): print(l1[i]+l2[i])

0
2
4
6
8


In [18]:
np.zeros((8,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.array([[1,3,4],[3,7,8]])

array([[1, 3, 4],
       [3, 7, 8]])

In [23]:
x=np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]])

In [27]:
x

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [28]:
x[2]

array([ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ])

In [29]:
x

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [30]:
x[:,2]

array([5.5, 4. , 2.1])

In [31]:
x

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [32]:
x[:,5]

array([ 2.4, -9. , -2. ])

In [40]:
x=np.array([[[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]],
            [[12, 13.2, 5.51, -6.41, -21.2, 2.41], [11, 212, 14, 0.11, 51.3, -91], [31, 11, 21, 2.1, 1.21, -12]]])

In [34]:
x

array([[[ 2.00e+00,  3.20e+00,  5.50e+00, -6.40e+00, -2.20e+00,
          2.40e+00],
        [ 1.00e+00,  2.20e+01,  4.00e+00,  1.00e-01,  5.30e+00,
         -9.00e+00],
        [ 3.00e+00,  1.00e+00,  2.10e+00,  2.10e+01,  1.10e+00,
         -2.00e+00]],

       [[ 1.20e+01,  1.32e+01,  5.51e+00, -6.41e+00, -2.12e+01,
          2.41e+00],
        [ 1.10e+01,  2.12e+02,  1.40e+01,  1.10e-01,  5.13e+01,
         -9.10e+01],
        [ 3.10e+01,  1.10e+01,  2.10e+01,  2.10e+00,  1.21e+00,
         -1.20e+01]]])

In [35]:
x[0]

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [36]:
x[1]

array([[ 1.20e+01,  1.32e+01,  5.51e+00, -6.41e+00, -2.12e+01,  2.41e+00],
       [ 1.10e+01,  2.12e+02,  1.40e+01,  1.10e-01,  5.13e+01, -9.10e+01],
       [ 3.10e+01,  1.10e+01,  2.10e+01,  2.10e+00,  1.21e+00, -1.20e+01]])

In [38]:
x[0,1]

array([ 1. , 22. ,  4. ,  0.1,  5.3, -9. ])

In [41]:
x[0,:,1]

array([ 3.2, 22. ,  1. ])

In [42]:
x

array([[[ 2.00e+00,  3.20e+00,  5.50e+00, -6.40e+00, -2.20e+00,
          2.40e+00],
        [ 1.00e+00,  2.20e+01,  4.00e+00,  1.00e-01,  5.30e+00,
         -9.00e+00],
        [ 3.00e+00,  1.00e+00,  2.10e+00,  2.10e+01,  1.10e+00,
         -2.00e+00]],

       [[ 1.20e+01,  1.32e+01,  5.51e+00, -6.41e+00, -2.12e+01,
          2.41e+00],
        [ 1.10e+01,  2.12e+02,  1.40e+01,  1.10e-01,  5.13e+01,
         -9.10e+01],
        [ 3.10e+01,  1.10e+01,  2.10e+01,  2.10e+00,  1.21e+00,
         -1.20e+01]]])

In [43]:
x[1,:,0]

array([12., 11., 31.])

In [44]:
[range(4), range(10, 14)] 

[range(0, 4), range(10, 14)]

In [45]:
x=np.array([range(4), range(10, 14)] )

In [46]:
x

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [47]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
b = np.arange(1,9)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
a = b.reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
c = np.array([1,2])
c

array([1, 2])

In [63]:
a + c

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [58]:
d = c.reshape(2,1)
d

array([[1],
       [2]])

In [59]:
b + d

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [64]:
a=[7,9,-9,8,3]

In [65]:
b=np.array(a)

In [67]:
b[b%2==0]

array([8])

In [68]:
b[[4,1,3]]

array([3, 9, 8])

In [70]:
np.square(b)

array([49, 81, 81, 64,  9], dtype=int32)

In [72]:
salary = np.array([-1,100000,200000,300000])

In [73]:
np.where(salary<0,10000,salary)

array([ 10000, 100000, 200000, 300000])

In [75]:
np.where(salary<0,np.mean(salary),salary)

array([149999.75, 100000.  , 200000.  , 300000.  ])

In [77]:
salary.T

array([    -1, 100000, 200000, 300000])

In [78]:
np.transpose(salary)

array([    -1, 100000, 200000, 300000])

In [79]:
np.cumsum(salary)

array([    -1,  99999, 299999, 599999], dtype=int32)

In [80]:
np.cumprod(salary)

array([        -1,    -100000, 1474836480,  593035264], dtype=int32)